source 'https://rubygems.org'

gem 'rails', '7.0.2.1'
gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', github: 'rails/sass-rails', branch: '5-0-stable'
  gem 'coffee-rails', '~> 5.0.0'
  gem "uglifier", ">= 4.2.0"
end

gem 'jquery-rails'



